### ISSUE TITLE
Panic in the tests (37a9373)

### ISSUE THREAD

**Issue by ninedraft** [amit-davidson/Chronos#14]
Running on 37a9373

```bash
go test -race ./e2e-tests/
```

will cause

```
--- FAIL: TestE2E (3.24s)
    --- FAIL: TestE2E/Lock (3.24s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 22 [running]:
testing.tRunner.func1.1(0x9b86a0, 0xc000e6a9c0)
	/usr/lib/go/src/testing/testing.go:1076 +0x46a
testing.tRunner.func1(0xc000082d80)
	/usr/lib/go/src/testing/testing.go:1079 +0x636
panic(0x9b86a0, 0xc000e6a9c0)
	/usr/lib/go/src/runtime/panic.go:975 +0x3e9
github.com/amit-davidson/Chronos/e2e-tests/testutils.GetRelativePath(0x1a09dc, 0xc000f9ca00, 0xc000641bf8, 0x0)
	/dev/pet/Chronos/e2e-tests/testutils/JsonDomains.go:68 +0x276
github.com/amit-davidson/Chronos/e2e-tests/testutils.LocksetToJSON(0xc003570030, 0x8db85e)
	/dev/pet/Chronos/e2e-tests/testutils/JsonDomains.go:48 +0x1e5
github.com/amit-davidson/Chronos/e2e-tests/testutils.NewTestResult(0xc003570030, 0xc003570070, 0x2, 0x2, 0xc0037fbf08)
	/dev/pet/Chronos/e2e-tests/testutils/utils.go:18 +0x56
github.com/amit-davidson/Chronos/e2e-tests.TestE2E.func1(0xc000082d80)
	/dev/pet/Chronos/e2e-tests/summary_test.go:187 +0x599
testing.tRunner(0xc000082d80, 0xc0000963f0)
	/usr/lib/go/src/testing/testing.go:1127 +0x203
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1178 +0x797
FAIL	github.com/amit-davidson/Chronos/e2e-tests	3.287s
FAIL
```

**Comment by ninedraft** [comment]
I think I'll take these if nobody objecting

**Comment by amit-davidson** [comment]
Fixed by: https://github.com/amit-davidson/Chronos/pull/16
